### ISSUE TITLE
Hafta 3 Çalışma sorusu 1

### ISSUE THREAD

**Issue by batuhannoz** [MelihEmreGuler/Duzce-Universitesi-Algoritma-2-Dersi#1]
https://github.com/MelihEmreGuler/Duzce-Universitesi-Algoritma-2-Dersi/blob/main/Algoritma%20Ders%203/CalismaSorulari/Soru1/Cevaplar.txt

`c) Termometre t(33.4, "santigrat");`

 Şıkkı yanlış olarak işaretlenmiş doğru olması gerekmez mi? Float ve string alan yapıcı fonksiyon verilmiş.  

`Termometre (float _deger, string _birim): deger(_deger), birim(_birim){}`

**Comment by melihemreguler** [comment]
@batuhannoz Evet doğru olması gerekir. Haber verdiğin için teşekkür ederim. Değiştirdim.
